export { default as socialLine } from './social-line.svg'
export { default as socialFacebook } from './social-facebook.svg'
export { default as socialInstagram } from './social-instagram.svg'
export { default as socialTiktok } from './social-tiktok.svg'
export { default as socialFacebookDark } from './social-facebook-dark.svg'
export { default as socialInstagramDark } from './social-instagram-dark.svg'
export { default as socialLineDark } from './social-line-dark.svg'

export { default as aboutIcon1 } from './about-icon-1.png'
export { default as aboutIcon2 } from './about-icon-2.png'
export { default as aboutIcon3 } from './about-icon-3.png'
