export { default as socialLine } from './social-line.svg'
export { default as socialFacebook } from './social-facebook.svg'
export { default as socialInstagram } from './social-instagram.svg'
export { default as socialTiktok } from './social-tiktok.svg'
export { default as socialFacebookDark } from './social-facebook-dark.svg'
export { default as socialInstagramDark } from './social-instagram-dark.svg'
export { default as socialLineDark } from './social-line-dark.svg'

export { default as socialFacebookSolid } from './social-facebook-solid.svg'
export { default as socialInstagramSolid } from './social-instagram-solid.svg'
export { default as socialTiktokSolid } from './social-tiktok-solid.svg'
export { default as socialLineSolid } from './social-line-solid.svg'
