import {
  certificate1,
  certificate2,
  certificate3,
  certificate4,
  certificate5,
  certificate6,
  certificate7,
  certificate8,
  certificate9,
  certificate10,
  certificate11,
  certificate12,
  certificate13,
  certificate14,
  certificate15,
  certificate16,
  certificate17,
} from '../certificate-images'

export const certificateList = [
  {
    id: 1,
    certificate_name_th: 'certificate-1',
    certificate_name_en: 'certificate-1',
    image_url: certificate1,
  },
  {
    id: 2,
    certificate_name_th: 'certificate-2',
    certificate_name_en: 'certificate-2',
    image_url: certificate2,
  },
  {
    id: 3,
    certificate_name_th: 'certificate-3',
    certificate_name_en: 'certificate-3',
    image_url: certificate3,
  },
  {
    id: 4,
    certificate_name_th: 'certificate-4',
    certificate_name_en: 'certificate-4',
    image_url: certificate4,
  },
  {
    id: 5,
    certificate_name_th: 'certificate-5',
    certificate_name_en: 'certificate-5',
    image_url: certificate5,
  },
  {
    id: 6,
    certificate_name_th: 'certificate-6',
    certificate_name_en: 'certificate-6',
    image_url: certificate6,
  },
  {
    id: 7,
    certificate_name_th: 'certificate-7',
    certificate_name_en: 'certificate-7',
    image_url: certificate7,
  },
  {
    id: 8,
    certificate_name_th: 'certificate-8',
    certificate_name_en: 'certificate-8',
    image_url: certificate8,
  },
  {
    id: 9,
    certificate_name_th: 'certificate-9',
    certificate_name_en: 'certificate-9',
    image_url: certificate9,
  },
  {
    id: 10,
    certificate_name_th: 'certificate-10',
    certificate_name_en: 'certificate-10',
    image_url: certificate10,
  },
  {
    id: 11,
    certificate_name_th: 'certificate-11',
    certificate_name_en: 'certificate-11',
    image_url: certificate11,
  },
  {
    id: 12,
    certificate_name_th: 'certificate-12',
    certificate_name_en: 'certificate-12',
    image_url: certificate12,
  },
  {
    id: 13,
    certificate_name_th: 'certificate-13',
    certificate_name_en: 'certificate-13',
    image_url: certificate13,
  },
  {
    id: 14,
    certificate_name_th: 'certificate-14',
    certificate_name_en: 'certificate-14',
    image_url: certificate14,
  },
  {
    id: 15,
    certificate_name_th: 'certificate-15',
    certificate_name_en: 'certificate-15',
    image_url: certificate15,
  },
  {
    id: 16,
    certificate_name_th: 'certificate-16',
    certificate_name_en: 'certificate-16',
    image_url: certificate16,
  },
  {
    id: 17,
    certificate_name_th: 'certificate-17',
    certificate_name_en: 'certificate-17',
    image_url: certificate17,
  },
]
