export const doctorsList = [
  {
    id: 1,
    image: '/storage/meen-doctor.webp',
    name_th: 'หมอ มีน',
    name_en: 'Doctor Meen',
    full_name_th: 'ธนวรรณ โชควัฒนคุปต์',
    full_name_en: 'Thanawan Chokwatanakup',
    caption_th: '" หมออยากให้ทุกคนเป็นตัวเองในเวอร์ชันที่ดีที่สุด "',
    caption_en: '" As your doctor, I want you to be the best version of yourself. "',
    qualifications_th:
      'M.D., M.Sc.Dermatology \n Fellowship in Laser & Cosmetic Dermatology, \n Florida International University',
    qualifications_en:
      'M.D., M.Sc.Dermatology \n Fellowship in Laser & Cosmetic Dermatology, \n Florida International University',
    specialists: [
      'Dermal Fillers and Botulinum Toxin',
      'Skin Laser Treatments',
      'Scar and Acne Scar Treatments',
      'Non-surgical Lifting and Facial Contouring',
      'Acne, Melasma, and Freckle Treatments',
    ],
    medical_school: [
      'M.D., Faculty of medicine, Prince of Songkla University, Thailand',
      'Master of Science in Dermatology, Chulabhorn International College of Medicine Thammasat University, Bangkok, Thailand',
      'Fellowship Training Program in General Dermatology & MOHS Surgery, Herbert Wertheim College of Medicine, Florida International University',
      'Fellowship Training Program in Laser & Cosmetic Dermatology, Herbert Wertheim College of Medicine, Florida International University',
    ],
    certificates: [
      'Certificate Expert Training Discovery Pico: Clinic Application of Discovery Picosecond Laser in Aesthetic & Clinical Dermatology, Bangkok, Thailand',
      'Certificate Sculptra Exclusive Hands-on Workshop, Bangkok, Thailand',
      'Certified Sculptra Injector',
      'Certificate Superiority of Injectable PALLA/HA, Bangkok, Thailand',
      'Certificate The Exclusive Ultraformer Ⅲ Training, Bangkok, Thailand',
      'Certificate Siriraj - LG Cadaver And Hands-On Workshop For Fillers Injection, Bangkok, Thailand',
      'Certificate LG Aesthetics Academy: Classy Sexy Trendy Lips, Yvoire Navigator Workshop, Bangkok, Thailand',
      'Certificate Multidisciplinary Approach of Botulinum Toxin for Face and Neck: A Practical Use, THAICOSDERM, Bangkok, Thailand',
      "Certificate 2023 H.E.L.F (Hugel Expert Leader's Forum), Bangkok, Thailand",
      'Certificate Integrated Aesthetic Course, Bangkok, Thailand',
      'Certificate Advanced Filler Injection, Bangkok, Thailand',
      'Certificate Elegant Cheeks & Eyes, Bangkok, Thailand',
      'Certificate Foxy Eyes and Submental Lift, Bangkok, Thailand',
      'Certificate AMC Lips Injection Workshop, Bangkok, Thailand',
      'Certificate 6th Cadaver Workshop for Fillers Injection at Siriraj Training and Education Center for Clinical Skills (SiTEC), Bangkok, Thailand',
      'Certificate the CICM 2024 Aesthetic Dermatology Conference: Fundamental to Future held by Chulabhorn International College of Medicine, Bangkok, Thailand',
      'Certificate the CICM 2024 Aesthetic Dermatology Conference: Hand-on Cadaver Workshop held by Chulabhorn International College of Medicine, Bangkok, Thailand',
      'Certificate Technical Training in Gynecology Restoration workshop by HA Dermal Filler, KNA Interpharma, Bangkok, Thailand',
      "Certificate Basic Training Lecture 'Tesslift Soft' by Certified Trainer, Bangkok, Thailand",
      'Certificate The Stand Alone Lecture Weight Expert: The Power of Daily Weight Management, Bangkok, Thailand',
    ],
  },
  // {
  //   id: 2,
  //   image: '/storage/meen-doctor.webp',
  //   name_th: 'หมอ มีน',
  //   name_en: 'Doctor Meen',
  //   full_name_th: 'ธนวรรณ โชควัฒนคุปต์',
  //   full_name_en: 'Thanawan Chokwatanakup',
  //   caption_th: '" หมออยากให้ทุกคนเป็นตัวเองในเวอร์ชันที่ดีที่สุด "',
  //   caption_en: '" As your doctor, I want you to be the best version of yourself. "',
  //   qualifications_th:
  //     'M.D., M.Sc.Dermatology \n Fellowship in Laser & Cosmetic Dermatology, \n Florida International University',
  //   qualifications_en:
  //     'M.D., M.Sc.Dermatology \n Fellowship in Laser & Cosmetic Dermatology, \n Florida International University',
  //   specialists: [
  //     'Dermal Fillers and Botulinum Toxin',
  //     'Skin Laser Treatments',
  //     'Scar and Acne Scar Treatments',
  //     'Non-surgical Lifting and Facial Contouring',
  //     'Acne, Melasma, and Freckle Treatments',
  //   ],
  //   medical_school: [
  //     'M.D., Faculty of medicine, Prince of Songkla University, Thailand',
  //     'Master of Science in Dermatology, Chulabhorn International College of Medicine Thammasat University, Bangkok, Thailand',
  //     'Fellowship Training Program in General Dermatology & MOHS Surgery, Herbert Wertheim College of Medicine, Florida International University',
  //     'Fellowship Training Program in Laser & Cosmetic Dermatology, Herbert Wertheim College of Medicine, Florida International University',
  //   ],
  //   certificates: [
  //     'Certificate Expert Training Discovery Pico: Clinic Application of Discovery Picosecond Laser in Aesthetic & Clinical Dermatology, Bangkok, Thailand',
  //     'Certificate Sculptra Exclusive Hands-on Workshop, Bangkok, Thailand',
  //     'Certified Sculptra Injector',
  //     'Certificate Superiority of Injectable PALLA/HA, Bangkok, Thailand',
  //     'Certificate The Exclusive Ultraformer Ⅲ Training, Bangkok, Thailand',
  //     'Certificate Siriraj - LG Cadaver And Hands-On Workshop For Fillers Injection, Bangkok, Thailand',
  //     'Certificate LG Aesthetics Academy: Classy Sexy Trendy Lips, Yvoire Navigator Workshop, Bangkok, Thailand',
  //     'Certificate Multidisciplinary Approach of Botulinum Toxin for Face and Neck: A Practical Use, THAICOSDERM, Bangkok, Thailand',
  //     "Certificate 2023 H.E.L.F (Hugel Expert Leader's Forum), Bangkok, Thailand",
  //     'Certificate Integrated Aesthetic Course, Bangkok, Thailand',
  //     'Certificate Advanced Filler Injection, Bangkok, Thailand',
  //     'Certificate Elegant Cheeks & Eyes, Bangkok, Thailand',
  //     'Certificate Foxy Eyes and Submental Lift, Bangkok, Thailand',
  //     'Certificate AMC Lips Injection Workshop, Bangkok, Thailand',
  //     'Certificate 6th Cadaver Workshop for Fillers Injection at Siriraj Training and Education Center for Clinical Skills (SiTEC), Bangkok, Thailand',
  //     'Certificate the CICM 2024 Aesthetic Dermatology Conference: Fundamental to Future held by Chulabhorn International College of Medicine, Bangkok, Thailand',
  //     'Certificate the CICM 2024 Aesthetic Dermatology Conference: Hand-on Cadaver Workshop held by Chulabhorn International College of Medicine, Bangkok, Thailand',
  //     'Certificate Technical Training in Gynecology Restoration workshop by HA Dermal Filler, KNA Interpharma, Bangkok, Thailand',
  //     "Certificate Basic Training Lecture 'Tesslift Soft' by Certified Trainer, Bangkok, Thailand",
  //     'Certificate The Stand Alone Lecture Weight Expert: The Power of Daily Weight Management, Bangkok, Thailand',
  //   ],
  // },
]
