import {
  ourPride1,
  ourPride2,
  ourPride3,
  ourPride4,
  ourPride5,
  ourPride6,
  ourPride7,
  ourPride8,
  ourPride9,
  ourPride10,
  ourPride11,
  ourPride12,
  ourPride13,
  ourPride14,
  ourPride15,
  ourPride16,
  ourPride17,
  ourPride18,
  ourPride19,
  ourPride20,
  ourPride21,
  ourPride22,
  ourPride23,
  ourPride24,
  ourPride25,
} from '../our-pride'

export const ourPrideList = [
  {
    id: 1,
    our_pride_name_th: 'ourPride1-1',
    our_pride_name_en: 'ourPride1-1',
    image_url: ourPride1,
  },
  {
    id: 2,
    our_pride_name_th: 'ourPride2-2',
    our_pride_name_en: 'ourPride2-2',
    image_url: ourPride2,
  },
  {
    id: 3,
    our_pride_name_th: 'ourPride3-3',
    our_pride_name_en: 'ourPride3-3',
    image_url: ourPride3,
  },
  {
    id: 4,
    our_pride_name_th: 'ourPride4-4',
    our_pride_name_en: 'ourPride4-4',
    image_url: ourPride4,
  },
  {
    id: 5,
    our_pride_name_th: 'ourPride5-5',
    our_pride_name_en: 'ourPride5-5',
    image_url: ourPride5,
  },
  {
    id: 6,
    our_pride_name_th: 'ourPride6-6',
    our_pride_name_en: 'ourPride6-6',
    image_url: ourPride6,
  },
  {
    id: 7,
    our_pride_name_th: 'ourPride7-7',
    our_pride_name_en: 'ourPride7-7',
    image_url: ourPride7,
  },
  {
    id: 8,
    our_pride_name_th: 'ourPride8-8',
    our_pride_name_en: 'ourPride8-8',
    image_url: ourPride8,
  },
  {
    id: 9,
    our_pride_name_th: 'ourPride9-9',
    our_pride_name_en: 'ourPride9-9',
    image_url: ourPride9,
  },
  {
    id: 10,
    our_pride_name_th: 'ourPride10-10',
    our_pride_name_en: 'ourPride10-10',
    image_url: ourPride10,
  },
  {
    id: 11,
    our_pride_name_th: 'ourPride11-11',
    our_pride_name_en: 'ourPride11-11',
    image_url: ourPride11,
  },
  {
    id: 12,
    our_pride_name_th: 'ourPride12-12',
    our_pride_name_en: 'ourPride12-12',
    image_url: ourPride12,
  },
  {
    id: 13,
    our_pride_name_th: 'ourPride13-13',
    our_pride_name_en: 'ourPride13-13',
    image_url: ourPride13,
  },
  {
    id: 14,
    our_pride_name_th: 'ourPride14-14',
    our_pride_name_en: 'ourPride14-14',
    image_url: ourPride14,
  },
  {
    id: 15,
    our_pride_name_th: 'ourPride15-15',
    our_pride_name_en: 'ourPride15-15',
    image_url: ourPride15,
  },
  {
    id: 16,
    our_pride_name_th: 'ourPride16-16',
    our_pride_name_en: 'ourPride16-16',
    image_url: ourPride16,
  },
  {
    id: 17,
    our_pride_name_th: 'ourPride17-17',
    our_pride_name_en: 'ourPride17-17',
    image_url: ourPride17,
  },
  {
    id: 18,
    our_pride_name_th: 'ourPride18-18',
    our_pride_name_en: 'ourPride18-18',
    image_url: ourPride18,
  },
  {
    id: 19,
    our_pride_name_th: 'ourPride19-19',
    our_pride_name_en: 'ourPride19-19',
    image_url: ourPride19,
  },
  {
    id: 20,
    our_pride_name_th: 'ourPride20-20',
    our_pride_name_en: 'ourPride20-20',
    image_url: ourPride20,
  },
  {
    id: 21,
    our_pride_name_th: 'ourPride21-21',
    our_pride_name_en: 'ourPride21-21',
    image_url: ourPride21,
  },
  {
    id: 22,
    our_pride_name_th: 'ourPride22-22',
    our_pride_name_en: 'ourPride22-22',
    image_url: ourPride22,
  },
  {
    id: 23,
    our_pride_name_th: 'ourPride23-23',
    our_pride_name_en: 'ourPride23-23',
    image_url: ourPride23,
  },
  {
    id: 24,
    our_pride_name_th: 'ourPride24-24',
    our_pride_name_en: 'ourPride24-24',
    image_url: ourPride24,
  },
  {
    id: 25,
    our_pride_name_th: 'ourPride25-25',
    our_pride_name_en: 'ourPride25-25',
    image_url: ourPride25,
  },
]
