import {
  reviewFiller1,
  reviewFiller2,
  reviewFiller3,
  reviewFiller4,
  reviewFiller5,
  reviewFiller6,
  reviewFiller7,
  reviewFiller8,
  reviewFiller9,
  reviewPico1,
  reviewPico2,
  reviewPico3,
  reviewPico4,
  reviewPico5,
  reviewPico6,
  reviewPico7,
  reviewPico8,
  reviewPico9,
  reviewPico10,
  reviewPico11,
  reviewPico12,
  reviewUltraformer1,
  reviewUltraformer2,
  reviewUltraformer3,
  reviewUltraformer4,
  reviewUltraformer5,
  reviewUltraformer6,
  reviewUltraformer7,
  reviewUltraformer8,
  reviewUltraformer9,
  reviewUltraformer10,
  reviewUltraformer11,
  reviewUltraformer12,
  reviewBotox1,
  reviewBotox2,
  reviewBotox3,
} from '../review-images'

export const reviewsList = [
  // Filler
  {
    id: 1,
    image: reviewFiller1,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 2,
    image: reviewFiller2,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 3,
    image: reviewFiller3,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 4,
    image: reviewFiller4,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 5,
    image: reviewFiller5,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 6,
    image: reviewFiller6,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 7,
    image: reviewFiller7,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 8,
    image: reviewFiller8,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },
  {
    id: 9,
    image: reviewFiller9,
    category_th: 'โปรแกรมฟิลเลอร์ปาก',
    category_en: 'Filler',
    category_order: 1,
  },

  // Pico
  {
    id: 1,
    image: reviewPico1,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 2,
    image: reviewPico2,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 3,
    image: reviewPico3,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 4,
    image: reviewPico4,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 5,
    image: reviewPico5,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 6,
    image: reviewPico6,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 7,
    image: reviewPico7,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 8,
    image: reviewPico8,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 9,
    image: reviewPico9,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 10,
    image: reviewPico10,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 11,
    image: reviewPico11,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },
  {
    id: 12,
    image: reviewPico12,
    category_th: 'Picosecond Laser',
    category_en: 'Picosecond Laser',
    category_order: 2,
  },

  // Ultraformer
  {
    id: 1,
    image: reviewUltraformer1,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 2,
    image: reviewUltraformer2,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 3,
    image: reviewUltraformer3,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 4,
    image: reviewUltraformer4,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 5,
    image: reviewUltraformer5,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 6,
    image: reviewUltraformer6,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 7,
    image: reviewUltraformer7,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 8,
    image: reviewUltraformer8,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 9,
    image: reviewUltraformer9,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 10,
    image: reviewUltraformer10,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 11,
    image: reviewUltraformer11,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },
  {
    id: 12,
    image: reviewUltraformer12,
    category_th: 'Program Ultraformer',
    category_en: 'Program Ultraformer',
    category_order: 3,
  },

  // Botox
  {
    id: 1,
    image: reviewBotox1,
    category_th: 'โปรแกรมโบท็อกซ์',
    category_en: 'Botox',
    category_order: 4,
  },
  {
    id: 2,
    image: reviewBotox2,
    category_th: 'โปรแกรมโบท็อกซ์',
    category_en: 'Botox',
    category_order: 4,
  },
  {
    id: 3,
    image: reviewBotox3,
    category_th: 'โปรแกรมโบท็อกซ์',
    category_en: 'Botox',
    category_order: 4,
  },
]
